/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/posts": {
    /** 投稿作成 */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Post"];
        };
      };
      responses: {
        /** @description 正常系 */
        200: {
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
        /** @description Internal Server Error */
        500: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** 投稿 */
    Post: {
      userId: string;
      desc?: string;
      img?: string;
      likes?: (unknown)[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
