openapi: 3.1.0

info:
  title: SNS App Web API
  description: SNS App用API
  version: 1.0.0

servers:
  - url: http://localhost:4000

tags:
  - name: auth
    description: 認証の操作
  - name: posts
    description: 投稿の操作
  - name: users
    description: ユーザーの操作

paths:
  /api/posts:
    post:
      summary: 投稿作成
      tags:
        - posts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
              example:
                userId: '1'
                desc: '投稿本文'
                img: 'https://placehold.jp/600x400.png'
                likes: ['1']
        500:
          description: Internal Server Error

components:
  schemas:
    Post:
      title: 投稿
      type: object
      properties:
        userId:
          type: string
        desc:
          type: string
          maxLength: 200
        img:
          type: string
        likes:
          type: array
      required:
        - userId
