openapi: 3.1.0

info:
  title: SNS App Web API
  description: SNS App用API
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: local
  - url: http://localhost:3001
    description: mock

tags:
  - name: auth
    description: 認証の操作
  - name: posts
    description: 投稿の操作
  - name: users
    description: ユーザーの操作

paths:
  /api/users/:
    $ref: "./paths/users.yaml#/users"
  /api/users/{id}:
    $ref: "./paths/users.yaml#/user"
  /api/posts:
    $ref: "./paths/posts.yaml#/posts"
  /api/posts/{id}:
    $ref: "./paths/posts.yaml#/post"
  /api/posts/{id}/likes:
    $ref: "./paths/posts.yaml#/likes"
  /api/posts/timeline/{userId}:
    $ref: "./paths/posts.yaml#/timeline"
  /api/posts/profile/timeline/{userName}:
    $ref: "./paths/posts.yaml#/profileTimeline"

components:
  schemas:
    Error:
      title: Error
      type: object
      properties:
        error:
          type: array
          description: エラーメッセージ
          items:
            type: string
    User:
      $ref: "./schemas/users.yaml#/user"
    Post:
      $ref: "./schemas/posts.yaml#/post"